language: node_js
node_js:
  - "5.5"
  - "4.2"
  - "0.12"
  - "0.10"
branches:
  only:
    - master
script: "npm run test-cov"
after_script: "npm i coveralls && cat ./coverage/lcov.info | coveralls"

